name: moments
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  standard_searchbar: ^2.1.1
  nanoid2: ^2.0.1
  faker: ^2.2.0
  intl: ^0.20.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

fonts: 
  - family: Poppins
    fonts:
    - asset: assets/fonts/Poppins-Regular.ttf
    - asset: assets/fonts/Poppins-Bold.ttf
      weight: 700
    - asset: assets/fonts/Poppins-Italic.ttf
      style: italic